version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      
      - run:
        name: Install dependencies
        command: |
          apt-get -y -qq update
          apt-get -y -qq install python3.4-dev
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3.4 get-pip.py --user
          pip install awscli --upgrade --user
      
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync / s3://dev.sunnydoors.co.uk --delete
          
