version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            sudo apt-get install python3-setuptools
            sudo easy_install3 pip
            pip install awscli --upgrade --user

      - run:
          name: Publish to aws
          command: |               
            export PATH=~/.local/bin:$PATH
            source ~/.profile
            aws s3 sync /home/circleci/project s3://dev.sunnydoors.co.uk/$CIRCLE_BRANCH --delete
      
      - run:
          name: Query pull request comments
          command: |
            curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET https://api.github.com/repos/jshb/sunnydoors/pulls/3/comments
          
