version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    working_directory: /
    steps:
      - checkout
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync / s3://dev.sunnydoors.co.uk --delete
          
          
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
